# Project Name
spring.application.name=merchant-payment-service

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL in console 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console so you can see the tables in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Resilience4j Settings
resilience4j.circuitbreaker.instances.bankService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bankService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bankService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bankService.waitDurationInOpenState=10000
